server:
  port: 8761
spring:
  application:
    name: eureka-feign

eureka:
  client:
  serviceUrl:
      defaultZone: http://localhost:8762/eureka/
#  instance:
#      prefer-ip-address: true
#      ip-address: ${server.port}

