server:
  port: 8761
spring:
  application:
    name: config-server
  profiles:
    active: dev
eureka:
  client:
  serviceUrl:
      defaultZone: http://localhost:8762/eureka/
test: 11111111      
      
#  instance:
#      prefer-ip-address: true
#      ip-address: ${server.port}

